[build]
  command = "rm -rf dist && mkdir -p dist && cp index.html metadata.json dist/ && esbuild src/index.tsx --bundle --format=esm --outfile=dist/bundle.js --jsx=automatic --loader:.ts=ts --loader:.tsx=tsx --platform=browser --target=esnext --define:process.env.API_KEY='\"$API_KEY\"' --external:@google/genai --external:jspdf --external:pdfjs-dist --external:mammoth"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
