[build]
  # Use the build script from your package.json
  command = "vite build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[build.environment]
  API_KEY = "AIzaSyCWwrqGX3uOwW5UeA5P3G0zfqA2pq5jcDQ"
  NETLIFY_API_TOKEN = "nfp_pTcj8xGScWsGXSZugrPASgur1vJPuWJL4384"
  NETLIFY_SITE_ID = "98b37587-6540-4302-b7cf-555e32c1be78"
