[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  # Ensure all functions can use blobs & other Netlify features
  included_files = ["netlify/functions/**"]

[capabilities]
  blobs = true

# API routes redirect to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback (React / client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
