[build]
  command = """
    rm -rf dist && mkdir -p dist && cp index.html metadata.json dist/ && \
    esbuild src/index.tsx --bundle --format=esm --outfile=dist/index.js \
    --loader:.ts=ts --loader:.tsx=tsx \
    --platform=browser --target=esnext
  """
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[functions."*"]
  external_node_modules = ["@netlify/blobs"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
