[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Redirect API requests from frontend -> Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA Fallback (React Router support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
