[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  # Explicitly enable blobs and modern runtime
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]
  included_files = ["netlify/functions/**"]
  deno_import_map = "import_map.json"

[[plugins]]
  package = "@netlify/plugin-functions-core"

# Redirect API requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback (React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[capabilities]
  # Explicitly tell Netlify we are using Blobs
  blobs = true
