# This file configures the build and deployment settings for Netlify.

[build]
  # Command to build the site
  command = "npm run build"
  
  # Directory containing the serverless functions
  functions = "netlify/functions"
  
  # Directory to publish after the build is complete
  publish = "dist"

# Rewrite API requests to serverless functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback: redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
